# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def import_pods
    pod 'HaishinKit', '~> 0.10.5'
end

target 'ios-movstone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    platform :ios, '8.0'
    import_pods
end
